version: '3'
services:
  rails:
    build: .
    volumes:
      - .:/myapp:delegated
      - bundle:/usr/local/bundle:cached
      - /myapp/.git
      - /myapp/log
      - /myapp/tmp
      - /myapp/vendor
    ports:
      - 3000:3000
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
    volumes:
      - mysql:/var/lib/mysql
volumes:
  bundle:
  mysql:
